spring:
  application:
    name: SpringBootRest
  datasource:
    url: jdbc:mysql://localhost:3306/develop
    username: admin
    password: brigadier

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

